-- Ejecutar después de schema.sql. Todo esto se puede editar o borrar luego desde /admin.

INSERT INTO site_config (id, nombre, institucion, eslogan, descripcion_corta, mision, vision, contacto_email, contacto_telefono, contacto_direccion, contacto_horario)
VALUES (
  1,
  'Escuela de Informática',
  'Instituto Superior — Escuela de Informática',
  'Formamos criterio técnico, no solo usuarios de herramientas.',
  'Formamos profesionales en programación, redes, datos y sistemas, con una currícula actualizada y vínculo directo con el sector productivo.',
  'Formar profesionales de la informática con sólidos fundamentos técnicos, capacidad de resolución de problemas reales y compromiso con el desarrollo tecnológico de la región.',
  'Ser una referencia regional en formación informática, reconocida por la calidad de sus egresados y su articulación permanente con el sector productivo y académico.',
  'informes@escuelainformatica.edu.ar',
  '+54 380 000-0000',
  'Av. Tecnológica 123, La Rioja, Argentina',
  'Lunes a viernes de 8 a 20 hs'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO estadisticas (numero, etiqueta, orden) VALUES
  ('18', 'años formando profesionales', 1),
  ('1200+', 'egresados en el mercado laboral', 2),
  ('24', 'cursos y trayectos activos', 3),
  ('40+', 'convenios con empresas e instituciones', 4);

INSERT INTO logros (anio, titulo, detalle) VALUES
  ('2025', 'Acreditación de la Tecnicatura en Desarrollo de Software', 'El plan de estudios fue acreditado por el organismo evaluador provincial por un nuevo período de 6 años, destacando la actualización curricular en desarrollo web y datos.'),
  ('2024', 'Primer puesto en la Maratón Nacional de Programación (zona NOA)', 'Un equipo de tercer año representó a la escuela y obtuvo el primer puesto regional, clasificando a la instancia nacional del certamen.'),
  ('2024', 'Convenio de prácticas profesionales con parque tecnológico regional', 'Se firmó un convenio marco que permite a estudiantes avanzados realizar sus prácticas profesionales supervisadas en empresas del parque tecnológico.'),
  ('2023', 'Laboratorio de redes y ciberseguridad renovado', 'Con financiamiento de un programa de equipamiento tecnológico, se renovó por completo el laboratorio de redes utilizado en las prácticas de los cuatro años de cursada.'),
  ('2022', 'Publicación en jornadas nacionales de educación en informática', 'Docentes de la escuela presentaron una experiencia pedagógica sobre enseñanza de programación con proyectos reales, publicada en las actas de las jornadas.');

INSERT INTO eventos (slug, tipo, titulo, fecha, modalidad, descripcion, rol, enlace) VALUES
  ('seminario-ia-aplicada-2026', 'Seminario', 'Seminario de Inteligencia Artificial Aplicada', '14 de agosto de 2026', 'Presencial', 'Encuentro de dos jornadas sobre aplicaciones prácticas de IA en pequeñas y medianas empresas, con estudios de caso presentados por docentes y egresados.', 'Organizado por la Escuela de Informática', NULL),
  ('webinar-ciberseguridad-pymes', 'Webinar', 'Ciberseguridad para pymes: primeros pasos', '3 de julio de 2026', 'Virtual', 'Charla abierta a la comunidad sobre buenas prácticas de seguridad informática para pequeñas empresas, dictada por el equipo docente del área de redes.', 'Dictado por la Escuela de Informática', NULL),
  ('congreso-nacional-educacion-tecnologica-2025', 'Congreso', 'Congreso Nacional de Educación Tecnológica', 'Octubre de 2025', 'Presencial', 'La escuela participó con una ponencia sobre estrategias de enseñanza de programación basada en proyectos, ante representantes de instituciones de todo el país.', 'Participación con ponencia propia', NULL),
  ('webinar-carreras-tech-2025', 'Webinar', '¿Qué estudiar si me gusta la tecnología?', 'Noviembre de 2025', 'Virtual', 'Encuentro orientado a estudiantes secundarios y sus familias, para conocer las salidas laborales de cada trayecto formativo de la escuela.', 'Organizado por la Escuela de Informática', NULL),
  ('jornadas-redes-y-servidores-2025', 'Seminario', 'Jornadas de Redes y Administración de Servidores', 'Mayo de 2025', 'Presencial', 'Tres encuentros prácticos sobre virtualización, administración de servidores Linux y monitoreo de redes, abiertos a estudiantes y egresados.', 'Dictado por la Escuela de Informática', NULL),
  ('congreso-latam-software-libre-2024', 'Congreso', 'Congreso Latinoamericano de Software Libre', 'Septiembre de 2024', 'Híbrido', 'Delegación docente y estudiantil asistió y presentó un taller sobre contribución a proyectos de código abierto en etapa de formación.', 'Participación con taller propio', NULL);

INSERT INTO noticias (slug, titulo, fecha, categoria, resumen, contenido) VALUES
  ('inscripciones-abiertas-segundo-cuatrimestre-2026', 'Abrimos inscripciones para el segundo cuatrimestre 2026', '20 de julio de 2026', 'Institucional', 'Ya están disponibles los cupos para los cursos y trayectos que comienzan en agosto, incluyendo dos propuestas nuevas de ciberseguridad y ciencia de datos.',
   '["A partir de esta semana quedan abiertas las inscripciones para todos los cursos que inician en agosto. Este cuatrimestre se incorporan dos propuestas nuevas: un curso introductorio de Ciberseguridad y un trayecto de Ciencia de Datos con Python.", "Como en cuatrimestres anteriores, los cupos son limitados y se otorgan por orden de inscripción. Podés revisar el detalle de cada curso, su temario y el enlace de inscripción en la sección Cursos.", "Ante cualquier duda sobre equivalencias o becas, podés escribir a la escuela por los canales de contacto habituales."]'),
  ('equipo-estudiantil-primer-puesto-maraton', 'Nuestro equipo obtuvo el primer puesto en la Maratón Nacional de Programación', '2 de junio de 2026', 'Logros', 'Tres estudiantes de tercer año representaron a la escuela en la instancia regional del certamen y se clasificaron para la final nacional.',
   '["Un equipo integrado por tres estudiantes de tercer año participó de la instancia regional de la Maratón Nacional de Programación, obteniendo el primer puesto entre más de veinte instituciones participantes.", "El certamen consistió en la resolución de problemas algorítmicos bajo presión de tiempo, en equipos de hasta tres personas. El equipo de la escuela resolvió la totalidad de los ejercicios propuestos en el menor tiempo registrado.", "Con este resultado, el equipo clasificó a la instancia nacional, que se realizará en los próximos meses. La escuela acompañará la preparación con encuentros de entrenamiento semanales."]'),
  ('nuevo-laboratorio-redes', 'Renovamos el laboratorio de redes y ciberseguridad', '18 de marzo de 2026', 'Institucional', 'El laboratorio utilizado en las prácticas de redes fue renovado por completo, incorporando nuevo equipamiento para las cuatro cohortes de la escuela.',
   '["Con financiamiento de un programa de equipamiento tecnológico, la escuela renovó por completo el laboratorio de redes que utilizan los estudiantes de los cuatro años de la cursada.", "El nuevo equipamiento permite realizar prácticas de virtualización, administración de servidores y monitoreo de redes en condiciones similares a las de un entorno productivo real.", "El laboratorio también estará disponible para las jornadas y seminarios abiertos a la comunidad que organiza la escuela durante el año."]'),
  ('convenio-parque-tecnologico', 'Firmamos un convenio de prácticas profesionales con el parque tecnológico regional', '5 de febrero de 2026', 'Vinculación', 'El acuerdo permite a estudiantes avanzados realizar sus prácticas profesionales supervisadas en empresas del parque tecnológico de la región.',
   '["La escuela firmó un convenio marco con el parque tecnológico regional que habilita a estudiantes de los últimos años a realizar sus prácticas profesionales supervisadas en empresas radicadas allí.", "El convenio contempla tutorías conjuntas entre un referente de la empresa y un docente de la escuela, y prevé una primera cohorte de prácticas para el segundo semestre del año.", "Se espera que este tipo de acuerdos se repliquen con otras instituciones y empresas del sector durante los próximos cuatrimestres."]');

INSERT INTO cursos (slug, titulo, categoria, nivel, modalidad, duracion, inicio, cupos, resumen, resena, temario, destinatarios, formulario_url) VALUES
  ('programacion-web-full-stack', 'Programación Web Full Stack', 'Desarrollo', 'Inicial', 'Presencial', '6 meses (2 encuentros semanales)', '12 de agosto de 2026', '30 vacantes',
   'Desde la lógica de programación hasta una aplicación web completa, con frontend, backend y base de datos.',
   '["Este curso está pensado para quienes quieren empezar a programar desde cero y llegar, en seis meses, a construir una aplicación web completa y funcional.", "Se trabaja con proyectos reales desde las primeras semanas: cada unidad suma una capa nueva a un mismo proyecto, que crece hasta convertirse en una aplicación con usuarios, base de datos y una interfaz cuidada.", "Al finalizar, cada estudiante presenta su propio proyecto ante un panel docente, como cierre integrador del curso."]',
   '[{"unidad":"Unidad 1 — Lógica y fundamentos","contenidos":["Variables, tipos de datos y estructuras de control","Funciones y estructuras de datos básicas","Introducción a la resolución de problemas algorítmicos"]},{"unidad":"Unidad 2 — Frontend","contenidos":["HTML semántico y CSS moderno (Flexbox y Grid)","JavaScript: manipulación del DOM y eventos","Introducción a un framework de componentes (React)"]},{"unidad":"Unidad 3 — Backend y datos","contenidos":["Node.js y creación de una API REST","Bases de datos relacionales: modelado y consultas SQL","Autenticación básica de usuarios"]},{"unidad":"Unidad 4 — Proyecto integrador","contenidos":["Integración de frontend, backend y base de datos","Control de versiones con Git y despliegue básico","Presentación final del proyecto propio"]}]',
   'Sin conocimientos previos requeridos. Recomendado para mayores de 16 años con manejo básico de computadora.',
   'https://forms.google.com/reemplazar-por-formulario-programacion-web'),
  ('ciencia-de-datos-con-python', 'Ciencia de Datos con Python', 'Datos', 'Intermedio', 'Híbrido', '4 meses (1 encuentro semanal presencial + material virtual)', '18 de agosto de 2026', '25 vacantes',
   'Análisis y visualización de datos con Python, desde la limpieza de datos hasta modelos predictivos simples.',
   '["Un recorrido práctico por el trabajo con datos reales: cómo limpiarlos, explorarlos, visualizarlos y, finalmente, construir un primer modelo predictivo simple.", "Se trabaja sobre conjuntos de datos públicos de organismos oficiales, para que cada práctica tenga un contexto reconocible y aplicable a problemas reales de la región.", "Es el curso ideal para quienes ya programan y quieren orientarse hacia el análisis de datos o dar sus primeros pasos en ciencia de datos."]',
   '[{"unidad":"Unidad 1 — Python para datos","contenidos":["Repaso de Python orientado a análisis de datos","Librerías Pandas y NumPy","Limpieza y transformación de datos"]},{"unidad":"Unidad 2 — Análisis exploratorio","contenidos":["Estadística descriptiva aplicada","Visualización de datos con Matplotlib y Seaborn","Detección de patrones y valores atípicos"]},{"unidad":"Unidad 3 — Introducción al aprendizaje automático","contenidos":["Conceptos de aprendizaje supervisado","Modelos de regresión y clasificación simples","Evaluación básica de modelos"]},{"unidad":"Unidad 4 — Proyecto con datos reales","contenidos":["Trabajo con un conjunto de datos público a elección","Elaboración de un informe de resultados","Presentación final del análisis"]}]',
   'Recomendado para quienes tienen nociones básicas de programación (en cualquier lenguaje).',
   'https://forms.google.com/reemplazar-por-formulario-ciencia-de-datos'),
  ('ciberseguridad-fundamentos', 'Ciberseguridad: Fundamentos y Buenas Prácticas', 'Redes y Seguridad', 'Inicial', 'Virtual', '3 meses (1 encuentro semanal)', '20 de agosto de 2026', '40 vacantes',
   'Principios de seguridad informática, gestión de riesgos y buenas prácticas aplicables a personas y organizaciones.',
   '["Un curso introductorio para entender los principios de la ciberseguridad sin necesidad de conocimientos técnicos avanzados previos.", "Se abordan tanto los aspectos técnicos básicos (redes, contraseñas, cifrado) como los organizacionales (políticas, concientización de usuarios, gestión de incidentes).", "Incluye casos reales de incidentes de seguridad en pequeñas y medianas organizaciones, analizados en clase."]',
   '[{"unidad":"Unidad 1 — Principios de seguridad","contenidos":["Confidencialidad, integridad y disponibilidad","Tipos de amenazas y vectores de ataque comunes","Gestión básica de contraseñas y autenticación"]},{"unidad":"Unidad 2 — Seguridad de redes","contenidos":["Conceptos de firewall y segmentación de red","Redes Wi-Fi seguras","Introducción a VPN y cifrado de tráfico"]},{"unidad":"Unidad 3 — Seguridad organizacional","contenidos":["Políticas de seguridad y concientización de usuarios","Gestión básica de incidentes","Introducción a normativas de protección de datos"]}]',
   'Abierto al público en general. No requiere conocimientos técnicos previos.',
   'https://forms.google.com/reemplazar-por-formulario-ciberseguridad'),
  ('administracion-de-redes-y-servidores', 'Administración de Redes y Servidores Linux', 'Redes y Seguridad', 'Avanzado', 'Presencial', '5 meses (2 encuentros semanales)', '25 de agosto de 2026', '20 vacantes',
   'Diseño, configuración y administración de redes y servidores Linux en entornos virtualizados.',
   '["Un curso de orientación práctica para quienes quieren especializarse en la administración de infraestructura: redes, servidores y virtualización.", "Gran parte de las clases se dictan en el laboratorio de redes de la escuela, trabajando sobre topologías reales y servidores virtualizados.", "Está orientado a estudiantes avanzados o egresados que quieran profundizar en el área de infraestructura y sistemas."]',
   '[{"unidad":"Unidad 1 — Redes","contenidos":["Modelo TCP/IP y direccionamiento avanzado","Routing y switching","Diagnóstico y resolución de problemas de red"]},{"unidad":"Unidad 2 — Servidores Linux","contenidos":["Instalación y administración de servidores Linux","Gestión de usuarios, permisos y servicios","Automatización básica con scripts"]},{"unidad":"Unidad 3 — Virtualización","contenidos":["Máquinas virtuales y contenedores","Introducción a la administración con Docker","Monitoreo de servicios y recursos"]},{"unidad":"Unidad 4 — Proyecto de infraestructura","contenidos":["Diseño de una topología de red completa","Despliegue de servicios sobre servidores virtualizados","Presentación final del proyecto de infraestructura"]}]',
   'Recomendado para estudiantes avanzados o egresados con conocimientos básicos de redes.',
   'https://forms.google.com/reemplazar-por-formulario-redes-y-servidores'),
  ('introduccion-a-la-programacion', 'Introducción a la Programación', 'Desarrollo', 'Inicial', 'Virtual', '2 meses (1 encuentro semanal)', '10 de agosto de 2026', '50 vacantes',
   'Primer acercamiento a la lógica de programación, pensado para quienes nunca programaron antes.',
   '["Un curso breve e introductorio, ideal como primer paso antes de encarar un trayecto más largo como Programación Web Full Stack.", "Se trabaja con un lenguaje simple y didáctico, priorizando la comprensión de la lógica por sobre la sintaxis de un lenguaje en particular.", "Las clases combinan explicación teórica breve con ejercicios prácticos guiados en cada encuentro."]',
   '[{"unidad":"Unidad 1 — Primeros pasos","contenidos":["Qué es programar y cómo piensa una computadora","Variables y tipos de datos","Entrada y salida de datos"]},{"unidad":"Unidad 2 — Estructuras de control","contenidos":["Condicionales","Bucles y repeticiones","Ejercicios de lógica progresivos"]},{"unidad":"Unidad 3 — Estructuras de datos simples","contenidos":["Listas y arreglos","Funciones básicas","Proyecto final breve integrador"]}]',
   'Sin conocimientos previos requeridos. Abierto a todo público.',
   'https://forms.google.com/reemplazar-por-formulario-introduccion'),
  ('desarrollo-de-apps-moviles', 'Desarrollo de Aplicaciones Móviles', 'Desarrollo', 'Intermedio', 'Presencial', '4 meses (2 encuentros semanales)', '22 de agosto de 2026', '25 vacantes',
   'Diseño y desarrollo de aplicaciones móviles multiplataforma, desde la interfaz hasta la publicación.',
   '["Un curso para quienes ya tienen bases de programación y quieren dar el salto al desarrollo de aplicaciones móviles.", "Se trabaja con un framework multiplataforma para poder desarrollar una única aplicación que funcione tanto en Android como en iOS.", "El curso cierra con el armado de una aplicación propia, lista para ser publicada en una tienda de aplicaciones."]',
   '[{"unidad":"Unidad 1 — Fundamentos de desarrollo móvil","contenidos":["Diferencias entre desarrollo nativo y multiplataforma","Componentes de interfaz y navegación","Manejo de estado en la aplicación"]},{"unidad":"Unidad 2 — Datos y conectividad","contenidos":["Consumo de APIs desde la aplicación","Almacenamiento local de datos","Notificaciones básicas"]},{"unidad":"Unidad 3 — Publicación","contenidos":["Buenas prácticas de diseño de interfaz móvil","Preparación de la aplicación para publicación","Presentación final del proyecto"]}]',
   'Recomendado para quienes ya cuentan con conocimientos básicos de programación.',
   'https://forms.google.com/reemplazar-por-formulario-apps-moviles');
